# Generated by Django 4.2 on 2023-05-05 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('average_price', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('address_ko', models.CharField(max_length=120)),
                ('address_en', models.CharField(blank=True, max_length=120, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('type', models.CharField(choices=[('L', '점심'), ('M', '회식'), ('C', '카페')], max_length=1)),
                ('genre', models.CharField(choices=[('C', '중식'), ('I', '인도음식'), ('K', '한식'), ('j', '일식'), ('IT', '이탈리아음식'), ('B', '바'), ('W', '양식'), ('Ch', '치킨'), ('P', '피자'), ('Cf', '카페'), ('D', '디저트')], max_length=2)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good_cnt', models.IntegerField(default=0)),
                ('bad_cnt', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_review',
            },
        ),
    ]
