# Generated by Django 4.1.2 on 2022-11-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('average_price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('address_ko', models.CharField(max_length=120)),
                ('address_en', models.CharField(max_length=120)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('type', models.CharField(choices=[('L', 'Lunch'), ('M', 'Mess'), ('C', 'Cafe')], max_length=1)),
                ('genre', models.CharField(choices=[('C', 'Chinese'), ('I', 'Indian'), ('K', 'Korean'), ('j', 'Japanese'), ('I', 'Italian'), ('B', 'Bar'), ('W', 'Western'), ('Ch', 'Chicken'), ('P', 'Pizza'), ('Cf', 'Cafe'), ('D', 'Dessert')], max_length=2)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good_cnt', models.IntegerField(default=0)),
                ('bad_cnt', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_review',
            },
        ),
    ]
