# Generated by Django 4.1.2 on 2022-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.CharField(choices=[('1', 'CTO'), ('2', '연구개발팀'), ('3', '전략기술팀')], max_length=30, verbose_name='팀ID'),
        ),
    ]
