# Generated by Django 4.1.2 on 2022-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.CharField(choices=[('1', '아기소')], default='1', max_length=30, verbose_name='팀ID'),
        ),
    ]
