# Generated by Django 4.1.2 on 2022-11-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_anonymouse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='anonymouse_name',
            new_name='anonymous_name',
        ),
    ]
