# Generated by Django 4.2 on 2024-01-18 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('rating', models.FloatField(default=0)),
                ('average_price', models.IntegerField(default=0)),
                ('address_ko', models.CharField(default='', max_length=120)),
                ('address_en', models.CharField(max_length=120, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('type', models.CharField(choices=[('점심', '점심'), ('회식', '회식'), ('카페', '카페')], max_length=2)),
                ('genre', models.CharField(choices=[('중식', '중식'), ('인도음식', '인도음식'), ('동남아음식', '동남아음식'), ('한식', '한식'), ('일식', '일식'), ('이탈리아음식', '이탈리아음식'), ('바', '바'), ('양식', '양식'), ('치킨', '치킨'), ('피자', '피자'), ('카페', '카페'), ('디저트', '디저트'), ('호프', '호프'), ('주점', '주점')], max_length=10)),
            ],
            options={
                'db_table': 'app_restaurants_restaurant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good_cnt', models.IntegerField(default=0)),
                ('bad_cnt', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_restaurants_review',
            },
        ),
    ]
