# Generated by Django 4.2 on 2024-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants', '0002_restaurant_created_at_restaurant_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='genre',
            field=models.CharField(choices=[('중식', '중식'), ('인도음식', '인도음식'), ('동남아음식', '동남아음식'), ('한식', '한식'), ('일식', '일식'), ('이탈리아음식', '이탈리아음식'), ('바', '바'), ('분식', '분식'), ('양식', '양식'), ('치킨', '치킨'), ('피자', '피자'), ('카페', '카페'), ('디저트', '디저트'), ('호프', '호프'), ('주점', '주점')], max_length=10),
        ),
    ]
